var data = {
  name: "sheet1",
  freeze: "A1",
  styles: [
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
    },
    { font: { bold: true } },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      align: "center",
    },
    { font: { bold: true }, align: "center" },
    { align: "center" },
    { align: "center", color: "#1f4e7a" },
    { align: "center", color: "#1f4e7a", bgcolor: "#1f4e7a" },
    { align: "center", color: "#ffffff", bgcolor: "#1f4e7a" },
    { align: "center", bgcolor: "#5b9cd6" },
    { bgcolor: "#5b9cd6" },
    { align: "center", bgcolor: "#5b9cd6", font: { bold: true } },
    { bgcolor: "#538136" },
    { bgcolor: "#fdc101" },
    { bgcolor: "#fed964" },
    { bgcolor: "#bf8e01" },
    { bgcolor: "#ffc001" },
    { bgcolor: "#fe0000" },
    { bgcolor: "#fe0000", color: "#ffffff" },
    { bgcolor: "#c00000", color: "#ffffff" },
    { bgcolor: "#c00000", color: "#ffffff", font: { bold: true } },
    {
      align: "center",
      color: "#ffffff",
      bgcolor: "#1f4e7a",
      font: { bold: true },
    },
    { bgcolor: "#f4b184" },
    { bgcolor: "#c9c9c9" },
    { align: "center", bgcolor: "#9cc2e6", font: { bold: true } },
    { bgcolor: "#756f6f" },
    { bgcolor: "#9cc2e6" },
    { bgcolor: "#9cc2e6", font: { bold: true } },
    { bgcolor: "#c45a10" },
    { bgcolor: "#f4b184", font: { bold: true } },
    { bgcolor: "#c9c9c9", font: { bold: true } },
    { bgcolor: "#538136", font: { bold: true } },
    { bgcolor: "#ffc001", font: { bold: true } },
    { bgcolor: "#ffc001", font: { bold: false } },
    { bgcolor: "#c00000", color: "#ffffff", font: { bold: false } },
    { bgcolor: "#71ae47" },
    { bgcolor: "#a7d08c" },
    { bgcolor: "#a7d08c", font: { bold: true } },
    { bgcolor: "#a7d08c", font: { bold: true }, align: "right" },
    { bgcolor: "#a7d08c", align: "right" },
    { align: "right" },
    { bgcolor: "#ffffff" },
    { font: { bold: true }, align: "center", bgcolor: "#1f4e7a" },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#f4b184",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#f4b184",
      font: { bold: true },
    },
    { bgcolor: "#5b9cd6", color: "#ffffff" },
    {
      bgcolor: "#5b9cd6",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#5b9cd6",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
    },
    { bgcolor: "#5b9cd6", color: "#ffffff", font: { bold: true } },
    {
      bgcolor: "#0170c1",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
    },
    { bgcolor: "#0170c1", color: "#ffffff", font: { bold: true } },
    {
      bgcolor: "#1f4e7a",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
    },
    { bgcolor: "#1f4e7a", color: "#ffffff", font: { bold: true } },
    { font: { bold: false }, align: "center", bgcolor: "#1f4e7a" },
    {
      font: { bold: false },
      align: "center",
      bgcolor: "#1f4e7a",
      color: "#ffffff",
    },
    {
      align: "center",
      color: "#ffffff",
      bgcolor: "#1f4e7a",
      font: { bold: true },
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#a7d08c",
      font: { bold: true },
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#a7d08c",
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#c00000",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
    },
    { color: "#ffffff" },
    { bgcolor: "#ffffff", color: "#ffffff" },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      align: "right",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#fdc101",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#fdc101",
      font: { bold: true },
    },
    { bgcolor: "#fdc101", font: { bold: true } },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#fdc101",
      font: { bold: true },
      color: "#ffffff",
    },
    { bgcolor: "#fdc101", font: { bold: true }, color: "#ffffff" },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#fdc101",
      font: { bold: true },
      color: "#000100",
    },
    { bgcolor: "#fdc101", font: { bold: true }, color: "#000100" },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#fdc101",
      font: { bold: true, size: 12 },
      color: "#000100",
    },
    { bgcolor: "#fdc101", font: { bold: true, size: 12 }, color: "#000100" },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#fdc101",
      font: { bold: true, size: 12 },
      color: "#000100",
      valign: "middle",
    },
    {
      bgcolor: "#fdc101",
      font: { bold: true, size: 12 },
      color: "#000100",
      valign: "middle",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#fdc101",
      font: { bold: true, size: 12 },
      color: "#000100",
      valign: "middle",
      align: "center",
    },
    {
      bgcolor: "#fdc101",
      font: { bold: true, size: 12 },
      color: "#000100",
      valign: "middle",
      align: "center",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true, size: 12 },
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true, size: 12 },
      align: "center",
    },
    { align: "right", font: { bold: true } },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true, size: 12 },
      align: "right",
    },
    { align: "right", font: { bold: true, size: 12 } },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true, size: 12 },
      align: "right",
      bgcolor: "#fdc101",
    },
    { align: "right", font: { bold: true, size: 12 }, bgcolor: "#fdc101" },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true, size: 12 },
      align: "center",
      bgcolor: "#fdc101",
    },
    { align: "center", font: { bold: true, size: 12 }, bgcolor: "#fdc101" },
    {
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#ffffff",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      align: "center",
      bgcolor: "#9cc2e6",
      font: { bold: true },
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#c9c9c9",
      font: { bold: true },
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#538136",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#538136",
      font: { bold: true },
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#ffc001",
      font: { bold: true },
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#ffc001",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#756f6f",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      bgcolor: "#ffffff",
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
    },
    {
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      align: "center",
    },
    {
      bgcolor: "#ffffff",
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      align: "center",
    },
    {
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      align: "right",
    },
    {
      bgcolor: "#ffffff",
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      align: "right",
    },
    {
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      align: "right",
      format: "number",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      bgcolor: "#ffffff",
      color: "#000100",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      align: "right",
      format: "number",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      align: "center",
      format: "number",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#f4b184",
      font: { bold: true },
      format: "number",
    },
    {
      bgcolor: "#ffc001",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      bgcolor: "#756f6f",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      bgcolor: "#538136",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      bgcolor: "#ffc001",
      font: { bold: true },
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      bgcolor: "#c00000",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      format: "number",
    },
    {
      bgcolor: "#a7d08c",
      font: { bold: true },
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      bgcolor: "#a7d08c",
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      bgcolor: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      align: "right",
      format: "number",
    },
    {
      bgcolor: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "number",
      align: "right",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      bgcolor: "#ffc001",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      bgcolor: "#756f6f",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      bgcolor: "#f4b184",
      font: { bold: true },
      format: "usd",
    },
    {
      bgcolor: "#538136",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      bgcolor: "#ffc001",
      font: { bold: true },
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      bgcolor: "#c00000",
      color: "#ffffff",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      format: "usd",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      align: "right",
      format: "usd",
    },
    {
      bgcolor: "#a7d08c",
      font: { bold: true },
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      bgcolor: "#a7d08c",
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      align: "right",
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      format: "usd",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      align: "center",
      format: "usd",
    },
    {
      border: {
        bottom: ["thin", "#000"],
        top: ["thin", "#000"],
        left: ["thin", "#000"],
        right: ["thin", "#000"],
      },
      font: { bold: true },
      format: "usd",
    },
  ],
  merges: [
    "C0:K0",
    "F6:J6",
    "I7:J7",
    "F7:G7",
    "E25:F25",
    "B25:D25",
    "B19:C19",
    "B20:C20",
    "B21:C21",
    "G25:H25",
    "B6:C6",
    "B7:C7",
    "B8:C8",
    "B9:C9",
    "B10:C10",
    "B11:C11",
    "B12:C12",
    "B13:C13",
    "B14:C14",
    "B15:C15",
    "B16:C16",
    "B17:C17",
    "B18:C18",
    "B22:C22",
    "B2:E2",
    "G2:J2",
    "B1:J1",
    "B5:J5",
    "F19:J19",
    "B23:C23",
    "E20:J23",
    "B3:J3",
  ],
  rows: {
    0: { cells: { 1: { style: 0, merge: [0, 8] } } },
    1: {
      cells: {
        1: { merge: [0, 3], style: 75, text: "CANTIDAD DE VEHICULOS" },
        2: { style: 76 },
        3: { style: 76 },
        4: { style: 76 },
        5: { style: 78, text: "1" },
        6: { merge: [0, 3], style: 84, text: "CALCULO DE IMPUESTOS" },
        7: { style: 85 },
        8: { style: 85 },
        9: { style: 85 },
      },
    },
    2: { cells: { 1: { merge: [0, 8], style: 0 } } },
    3: {
      cells: {
        1: { text: "FOB TABLA", style: 65 },
        2: { text: "14340", style: 128 },
        3: { text: "FLETE", style: 65 },
        4: { text: "575", style: 128 },
        5: { text: "T/C", style: 65 },
        6: { text: "59.46", style: 128 },
        7: { style: 65, text: "FOB" },
        8: { style: 129, text: "15500" },
        9: { style: 0 },
      },
    },
    4: { cells: { 1: { style: 0, merge: [0, 8] } } },
    5: {
      cells: {
        1: { text: "FOB", style: 44, merge: [0, 1] },
        3: { text: "=IF(F17>0:F17:I16)", style: 125 },
        4: { text: "=D6*D11", style: 104, editable: false },
        5: { merge: [0, 4], text: "PARAMETROS", style: 55 },
        6: { style: 21 },
        7: { style: 21 },
        8: { style: 21 },
        9: { style: 21 },
      },
    },
    6: {
      cells: {
        1: { text: "FLETE", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=F18", style: 126 },
        4: { text: "=D7*D11", style: 104, editable: false },
        5: { text: "ADUANAS", style: 88, merge: [0, 1] },
        6: { style: 24 },
        7: { style: 0 },
        8: { merge: [0, 1], text: "USA", style: 88 },
        9: { style: 24 },
      },
    },
    7: {
      cells: {
        1: { text: "C&F", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=SUM(D6:D7)", style: 127 },
        4: { style: 104, editable: false },
        5: { style: 105, text: "=(E16*I17)+F9+F10+F11+F15" },
        6: { text: "TOTAL DGA", style: 44 },
        7: { style: 0 },
        8: { text: "=SUM(I9:I15)", style: 120 },
        9: { text: "TOTAL GASTOS", style: 44 },
      },
    },
    8: {
      cells: {
        1: { text: "SEGURO", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=14340*D26", style: 127 },
        4: { text: "=D9*D11", style: 104, editable: false },
        5: { text: "4500", style: 102 },
        6: { text: "PARQUEO", style: 89 },
        7: { style: 0 },
        8: { text: "575", style: 117 },
        9: { text: "FLETE", style: 89 },
      },
    },
    9: {
      cells: {
        1: { text: "CIF US$", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=SUM(D8:D9)", style: 127 },
        4: { style: 104, editable: false },
        5: { text: "258.26", style: 102 },
        6: { text: "DUA", style: 89 },
        7: { style: 0 },
        8: { text: "250", style: 117 },
        9: { text: "GRUA SUBASTA", style: 89 },
      },
    },
    10: {
      cells: {
        1: { text: "T/C", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=F16", style: 125 },
        4: { style: 104, editable: false },
        5: { text: "=(D31*D11)*I17", style: 117 },
        6: { text: "TASA S. ADUANERA", style: 89 },
        7: { style: 0 },
        8: { text: "300", style: 117 },
        9: { text: "DEALER FEE", style: 89 },
      },
    },
    11: {
      cells: {
        1: { style: 44, merge: [0, 1] },
        2: {},
        3: { style: 116 },
        4: { style: 104, editable: false },
        5: { text: "0", style: 102 },
        6: { text: "PORTUARIA", style: 89 },
        7: { style: 0 },
        8: { text: "95", style: 117 },
        9: { text: "ADUANAS", style: 89 },
      },
    },
    12: {
      cells: {
        1: { text: "CIF RD$", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=D10*D11", style: 113 },
        4: { text: "=E6+E7+E9", style: 104, editable: false },
        5: { text: "=C26", style: 102 },
        6: { text: "SEGURO", style: 89 },
        7: { style: 0 },
        8: { text: "0", style: 117 },
        9: { text: "GRUA PUERTOS", style: 89 },
      },
    },
    13: {
      cells: {
        1: { text: "GRAVAMEN", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=D13*D27", style: 113 },
        4: { style: 104, editable: false },
        5: { text: "=C27", style: 102 },
        6: { text: "GRAVAMEN", style: 89 },
        7: { style: 0 },
        8: { text: "0", style: 117 },
        9: { text: "OTROS GASTOS", style: 89 },
      },
    },
    14: {
      cells: {
        1: { text: "RD$", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=SUM(D13:D14)", style: 115 },
        4: { style: 104, editable: false },
        5: { text: "5000", style: 102 },
        6: { text: "ADUANERO", style: 89 },
        7: { style: 0 },
        8: { style: 121, text: "0" },
        9: { text: "BROKER FEE", style: 91 },
      },
    },
    15: {
      cells: {
        1: { text: "ITBIS", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=D15*D28", style: 113 },
        4: { text: "=D14+D16", style: 104, editable: false },
        5: { text: "=G4", style: 117, editable: false },
        6: { text: "TASA DOLAR", style: 89 },
        7: { style: 0 },
        8: { style: 122, text: "=i4", editable: false },
        9: { text: "FOB", style: 92 },
      },
    },
    16: {
      cells: {
        1: { text: "PLACA", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=D13*D29", style: 113 },
        4: { style: 104, text: "=IF(I17>1,J26,J25)", editable: false },
        5: { text: "=C4", style: 118, editable: false },
        6: { text: "FOB TABLA", style: 93 },
        7: { style: 0 },
        8: { style: 122, text: "=F2", editable: true },
        9: { text: "CANT. VEHICULOS", style: 92 },
      },
    },
    17: {
      cells: {
        1: { text: "CO2", style: 44, merge: [0, 1] },
        2: {},
        3: { text: "=D13*D30", style: 113 },
        4: { style: 104, text: "=D17+D18+H27", editable: false },
        5: { text: "=I9", style: 119 },
        6: { text: "FLETE RD", style: 94 },
        7: { style: 0 },
        8: { style: 123, text: "=I8+I16*I17" },
        9: { text: "CIF", style: 60 },
      },
    },
    18: {
      cells: {
        1: { merge: [0, 1], text: "TOTAL IMPUESTOS RD$", style: 51 },
        2: { style: 52 },
        3: { text: "=SUM(D16:D18)+D14+H27", style: 115 },
        4: {
          text: "=D19+F9+F10+F11+F12+F15+F26+H28+IF(C26<2,J27,0)",
          style: 104,
          editable: false,
        },
        5: { style: 0, merge: [0, 4] },
      },
    },
    19: {
      cells: {
        1: { merge: [0, 1], text: "COSTO VEHICULO RD$", style: 51 },
        2: { style: 52 },
        3: { style: 115, text: "=D11*I18" },
        4: { style: 0, editable: false, merge: [3, 5] },
      },
    },
    20: {
      cells: {
        1: { merge: [0, 1], text: "TOTAL", style: 51 },
        2: { style: 52 },
        3: { style: 115, text: "=SUM(D19:D20)" },
        4: { style: 0, editable: false },
      },
    },
    21: {
      cells: {
        1: { style: 60, merge: [0, 1], text: "TOTAL + GASTOS RD$" },
        2: { style: 20 },
        3: { style: 115, text: "=D20+E19" },
        4: { style: 0, editable: false },
      },
    },
    22: {
      cells: {
        1: { style: 60, merge: [0, 1], text: "TOAL EN DOLARES (US$)" },
        2: { style: 20 },
        3: { style: 124, text: "=D22/D11" },
      },
    },
    24: {
      cells: {
        1: { merge: [0, 2], text: "PROCENTAJES Y TASAS", style: 55 },
        2: { style: 21 },
        3: { style: 21 },
        4: { merge: [0, 1], style: 55, text: "EXTRAS" },
        5: { style: 21 },
        6: { style: 55, merge: [0, 1], text: "DGII" },
        7: { style: 21 },
        8: { style: 0 },
        9: { text: "=F11+E16", editable: false, style: 101 },
      },
    },
    25: {
      cells: {
        1: { text: "SEGURO %", style: 44 },
        2: { text: "2", style: 58 },
        3: { text: "=C26/100", style: 113, editable: false },
        4: { text: "TOTAL EXTRAS", style: 44 },
        5: { style: 115, text: "=SUM(F27:F30)" },
        6: { text: "2% CO2", style: 44 },
        7: { text: "0.02", style: 113 },
        8: { style: 0 },
        9: { text: "=(F11/I17)+E16", editable: false, style: 103 },
      },
    },
    26: {
      cells: {
        1: { text: "GRAVAMENT %", style: 44 },
        2: { text: "0", style: 58 },
        3: { text: "=C27/100", style: 113, editable: false },
        4: { text: "DEALER FEE", style: 44 },
        5: { style: 113, text: "30000" },
        6: { text: "MARBETE RD$", style: 44 },
        7: { text: "3000", style: 113 },
        8: { style: 0 },
        9: { text: "=D9*D11", editable: false, style: 99 },
      },
    },
    27: {
      cells: {
        1: { text: "ITBIS %", style: 44 },
        2: { text: "18", style: 58 },
        3: { text: "=C28/100", style: 113, editable: false },
        4: { text: "DELIVERY", style: 44 },
        5: { style: 113, text: "0.00" },
        6: { text: "GESTION PLACA RD$", style: 44 },
        7: { text: "2000", style: 113 },
        8: { style: 0 },
        9: { style: 0 },
      },
    },
    28: {
      cells: {
        1: { text: "PLACA %", style: 44 },
        2: { text: "17", style: 58 },
        3: { text: "=C29/100", style: 113, editable: false },
        4: { text: "SEGURO DE CARGA", style: 44 },
        5: { style: 113, text: "0.00" },
        6: { style: 44 },
        7: { style: 58 },
        8: { style: 0 },
        9: { style: 0 },
      },
    },
    29: {
      cells: {
        1: { text: "CO2 %", style: 44 },
        2: { text: "2", style: 58 },
        3: { text: "=C30/100", style: 113, editable: false },
        4: { text: "OTROS", style: 44 },
        5: { style: 113, text: "1700" },
        6: { style: 44 },
        7: { style: 58 },
        8: { style: 0 },
        9: { style: 0 },
      },
    },
    30: {
      cells: {
        1: { text: "TASA", style: 44 },
        2: { style: 58 },
        3: { text: "147.069", style: 113 },
        4: { style: 44 },
        5: { style: 58 },
        6: { style: 44 },
        7: { style: 58 },
        8: { style: 0 },
        9: { style: 0 },
      },
    },
    len: 100,
  },
  cols: {
    1: { width: 104 },
    3: { width: 138 },
    4: { width: 117 },
    5: { width: 118 },
    6: { width: 144 },
    7: { width: 102 },
    10: { width: 134 },
    len: 26,
  },
  validations: [],
  autofilter: {},
};
export default data;
